name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    name: Build&Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Install firebase
        run: npm install -g firebase-tools
      - name: select firebase project
        run: firebase use mathmatch --token ${{ secrets.FIREBASE_TOKEN }}
      - name: deploy to Firebase Hosting
        run: firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}
    